spring:
  application:
    name: config

  # Configuration for Spring Cloud Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nguyendangviet12022004/stack-overflow-clone-config
          cloneOnStart: true
          force-pull: true
  # profile
  profiles:
    active: git

#port
server:
  port: 8070

