spring:
  application:
    name: config

  # Configuration for Spring Cloud Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nguyendangviet12022004/stack-overflow-clone-config
          cloneOnStart: true
          force-pull: true
  # profile
  profiles:
    active: git

#encryption
encrypt:
  key-store:
    location: classpath:/server.jks
    password: password
    alias: secretkey
    secret: password

#healthcheck
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
        enabled: true
#port
server:
  port: 8070


#info
info:
  app:
    name: ${spring.application.name}
    description: Config Service
    version: 1.0.0
