spring:
  application:
    name: notification


  mongodb:
    authentication-database: admin
    database: ${NOTIFICATION_DB_DATABASE:notificationdb}
    port: ${NOTIFICATION_DB_PORT:27017}
    host: ${NOTIFICATION_DB_HOST:localhost}
    username: ${NOTIFICATION_DB_USERNAME:root}
    password: ${NOTIFICATION_DB_PASSWORD:password}

