services:

  #mail stmp server --------------------------------------------
  # mail-smtp:
  #   image: maildev/maildev
  #   container_name: mail-smtp
  #   ports:
  #     - "1080:1080"
  #     - "1025:1025"


  #rabbitmq
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - path: ../env/rabbitmq/rabbitmq.env
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  #db --------------------------------------------------------
  # user-db:
  #   image: mysql:8.0.44-debian
  #   container_name: user-db
  #   env_file:
  #     - path: ../env/user/user.db.env
  #   ports:
  #       - "33061:3306"
  #   volumes:
  #       - user-db-data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 20s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 40s


  # post-db:
  #   image: mysql:8.0.44-debian
  #   container_name: post-db
  #   env_file:
  #     - path: ../env/post/post.db.env
  #   ports:
  #     - "33062:3306"
  #   volumes:
  #     - "post-db-data:/var/lib/mysql"
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
  #     interval: 20s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 40s


  notification-db:
    image: mongo
    container_name: notification-db
    ports:
      - "27017:27017"
    volumes:
      - notification-db-data:/data/db
    env_file:
      - path: ../env/notification/notification.db.env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s


  #config server --------------------------------------
  config:
    build:
      context: ../config
      dockerfile: ./../Dockerfile
      args:
        - PORT=8070
    container_name: config
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    ports:
      - "8070:8070"
    depends_on:
      rabbitmq:
        condition: service_healthy

  #eureka server --------------------------------------
  eureka:
    build:
      context: ../eureka
      dockerfile: ./../Dockerfile
      args:
        - PORT=8761
    container_name: eureka
    ports:
        - "8761:8761"
    env_file:
      - ../env/eureka/eureka.prod.env
      - ../env/.env
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      config:
        condition: service_healthy

  #gateway server --------------------------------------
  gateway:
    build:
      context: ../gateway
      dockerfile: ./../Dockerfile
      args:
        - PORT=8080
    container_name: gateway
    volumes:
      - type: bind
        source: ./../key/public.pem
        target: /app/public.pem
        read_only: true
    ports:
      - "8080:8080"
    env_file:
      - ../env/gateway/gateway.prod.env
      - ../env/.env
    depends_on:
      eureka:
        condition: service_healthy

    #mail service --------------------------------------

  # #services
  # mail:
  #   build:
  #     context: ../mail
  #     dockerfile: ./../Dockerfile
  #     args:
  #       - PORT=8003
  #   container_name: mail
  #   ports:
  #       - "8003:8003"
  #   env_file:
  #       - ../env/mail/mail.prod.env
  #       - ../env/.env
  #   depends_on:
  #       eureka:
  #           condition: service_healthy
  #       mail-smtp:
  #           condition: service_healthy

  user:
    build:
      context: ../user
      dockerfile: ./../Dockerfile
      args:
        - PORT=8001
    container_name: user
    volumes:
      - type: bind
        source: ./../key/private.pem
        target: /app/private.pem
        read_only: true
    ports:
        - "8001:8001"
    env_file:
      - ../env/user/user.prod.env
      - ../env/.env
    depends_on:
      eureka:
        condition: service_healthy
      # user-db:
      #   condition: service_healthy
      rabbitmq:
        condition: service_healthy

  post:
    build:
      context: ../post
      dockerfile: ./../Dockerfile
      args:
        - PORT=8002
    container_name: post
    ports:
        - "8002:8002"
    env_file:
        - ../env/post/post.prod.env
        - ../env/.env
    depends_on:
      eureka:
        condition: service_healthy
      # post-db:
      #   condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification:
    build:
      context: ../notification
      dockerfile: ./../Dockerfile
      args:
        - PORT=8004
    container_name: notification
    ports:
        - "8004:8004"
    env_file:
      - ../env/notification/notification.prod.env
      - ../env/.env
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  ui:
    build:
      context: ../ui
    container_name: ui
    ports:
      - "80:8080"
#volumes
volumes:
#     user-db-data:
#       driver: local
#     post-db-data:
#       driver: local
    notification-db-data:
      driver: local
