services:

  #mail stmp server --------------------------------------------
  mail-smtp:
    image: maildev/maildev
    container_name: mail-smtp
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - backend-network

  #rabbitmq
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - path: ../env/rabbitmq/rabbitmq.env
    networks:
      - backend-network

  #db --------------------------------------------------------
  user-db:
    image: mysql:8.0.44-debian
    container_name: user-db
    env_file:
      - path: ../env/user/user.db.env
    ports:
        - "33061:3306"
    volumes:
        - user-db-data:/var/lib/mysql
    networks:
      - backend-network

  post-db:
    image: mysql:8.0.44-debian
    container_name: post-db
    env_file:
      - path: ../env/post/post.db.env
    ports:
      - "33062:3306"
    volumes:
      - "post-db-data:/var/lib/mysql"
    networks:
      - backend-network

  #config server --------------------------------------
  config:
    build:
      context: ../config
      dockerfile: ./../docker-compose/Dockerfile
      args:
        - PORT=8070

    container_name: config
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    ports:
      - "8070:8070"

  #eureka server --------------------------------------
  eureka:
    build:
      context: ./../eureka
    container_name: eureka
    ports:
        - "8761:8761"
    env_file:
      - ../env/eureka/eureka.prod.env
      - ../env/.env
    depends_on:
      - config


  #gateway server --------------------------------------
  gateway:
    build:
      context: ./../gateway
    container_name: gateway
    ports:
      - "8080:8080"
    env_file:
      - ../env/.env
    depends_on:
      - eureka

    #mail service --------------------------------------
  mail:
      build:
          context: ./../mail
      container_name: mail
      ports:
          - "8003:8003"
      env_file:
          - ../env/mail/mail.prod.env
          - ../env/.env
      depends_on:
          - eureka
          - mail-smtp
          - rabbitmq

#volumes
volumes:
    user-db-data:
      driver: local
    post-db-data:
      driver: local

#networks
networks:
    backend-network:
      driver: bridge