spring:
  application:
    name: post

  rabbitmq:
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
  #config server
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8070}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
